services:
  web:
    build: .
    command: ["./wait-for-it.sh", "db:5432", "--", "uwsgi", "--ini", "/code/prod/uwsgi/uwsgi.ini"]
#    restart: always
    volumes:
      - .:/code
    ports:
      - 8000:8000
    environment:
      - DJANGO_SETTINGS_MODULE=educa.settings.prod
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    depends_on:
      - db
      - cache

  daphne:
    build: .
    command: ["./wait-for-it.sh", "db:5432", "--", "daphne", "-u", "/code/daphne.sock", "educa.asgi:application"]
#    restart: always
    volumes:
      - .:/code
    environment:
      - DJANGO_SETTINGS_MODULE=educa.settings.prod
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    depends_on:
      - db
      - cache

  nginx:
    image: nginx:1.23.1
#    restart: always
    volumes:
      - ./prod/nginx:/etc/nginx/templates
      - .:/code
    ports:
      - "80:80"  # http
      - "443:443"

  db:
    image: postgres:14.5
#    restart: always
    volumes:
      - ./data/db:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
  cache:
    image: redis:7.0.4
#    restart: always
    volumes:
      - ./data/cache:/data

